// <auto-generated />
using System;
using CelsoMusic.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CelsoMusic.Repository.Migrations
{
    [DbContext(typeof(CelsoMusicContext))]
    [Migration("20220929014017_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CelsoMusic.Domain.Musica.Album", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtistaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistaID");

                    b.ToTable("Albuns", (string)null);
                });

            modelBuilder.Entity("CelsoMusic.Domain.Musica.Artista", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("Artistas", (string)null);
                });

            modelBuilder.Entity("CelsoMusic.Domain.Musica.Musica", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlbumID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID");

                    b.ToTable("Musicas", (string)null);
                });

            modelBuilder.Entity("CelsoMusic.Domain.Usuario.Playlist", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("Playlists", (string)null);
                });

            modelBuilder.Entity("MusicaPlaylist", b =>
                {
                    b.Property<Guid>("MusicasID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaylistsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MusicasID", "PlaylistsID");

                    b.HasIndex("PlaylistsID");

                    b.ToTable("MusicaPlaylist");
                });

            modelBuilder.Entity("CelsoMusic.Domain.Musica.Album", b =>
                {
                    b.HasOne("CelsoMusic.Domain.Musica.Artista", "Artista")
                        .WithMany("Albuns")
                        .HasForeignKey("ArtistaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("CelsoMusic.Domain.Musica.Musica", b =>
                {
                    b.HasOne("CelsoMusic.Domain.Musica.Album", "Album")
                        .WithMany("Musicas")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CelsoMusic.Domain.Musica.ValueObject.Duracao", "Duracao", b1 =>
                        {
                            b1.Property<Guid>("MusicaID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("Duracao");

                            b1.HasKey("MusicaID");

                            b1.ToTable("Musicas");

                            b1.WithOwner()
                                .HasForeignKey("MusicaID");
                        });

                    b.Navigation("Album");

                    b.Navigation("Duracao");
                });

            modelBuilder.Entity("MusicaPlaylist", b =>
                {
                    b.HasOne("CelsoMusic.Domain.Musica.Musica", null)
                        .WithMany()
                        .HasForeignKey("MusicasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelsoMusic.Domain.Usuario.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CelsoMusic.Domain.Musica.Album", b =>
                {
                    b.Navigation("Musicas");
                });

            modelBuilder.Entity("CelsoMusic.Domain.Musica.Artista", b =>
                {
                    b.Navigation("Albuns");
                });
#pragma warning restore 612, 618
        }
    }
}
